### ISSUE TITLE
Spam Protection?? 

### ISSUE THREAD

**Issue by codingstark-dev** [opxop/bookshelf#15]
I think there is no spam protection in https://books.opakholis.dev/api/notion ??

**Comment by opakholis** [comment]
thanks the issue @beprocoder, I didn't know that this would happen😲

is this possible to protect without tools like captcha? i have no idea about this

**Comment by codingstark-dev** [comment]
> thanks the issue @beprocoder, I didn't know that this would happen😲
> 
> is this possible to protect without tools like captcha? I have no idea about this

Maybe, you can implement a rate limit as expressjs have... See this https://github.com/vercel/next.js/discussions/12134

**Comment by opakholis** [comment]
ahh.. let me read it first, thank you!

**Comment by opakholis** [comment]
solved #16
